token = "XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ownerIds = [
    00000000000000000,
    00000000000000000,
]
prefixes = [
    "!",
    "?",
]
testGuildIds = [
    00000000000000000,
    00000000000000000,
]

[database]
serverName = "mydbservername"
name = "mydbname"
port = 5432
user = "mydbuser"
password = "mydbpassword"
