token = "<BOT-TOKEN>"
owner-ids = [
    12345678901234567,
    12345678901234567,
]
prefixes = [
    "@ping", # This allows ping as prefix.
    "!",
    "?",
]
test-guild-ids = [
    12345678901234567,
    12345678901234567,
]

[database]
server-name = "mydbservername"
port = 5432
name = "mydbname"
user = "mydbuser"
password = "mydbpassword"
